/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // OSDO v2 — New section
    {
      type: 'category',
      label: 'OSDO v2',
      collapsible: true,
      collapsed: false,
      items: [
        'v2/introduccion',
        'v2/novedades',
        'v2/migracion-v1-v2',
        {
          type: 'category',
          label: 'CLI Reference',
          items: [
            'v2/cli/instalacion',
            'v2/cli/comandos',
            'v2/cli/app-integracion',
            'v2/cli/variables-entorno',
          ],
        },
        {
          type: 'category',
          label: 'Las 22 Actions',
          items: [
            {
              type: 'category',
              label: 'Análisis de Código',
              items: ['v2/actions/sast', 'v2/actions/sca', 'v2/actions/secrets-scan'],
            },
            {
              type: 'category',
              label: 'Infraestructura y Contenedores',
              items: ['v2/actions/container-scan', 'v2/actions/iac-scan', 'v2/actions/build-security'],
            },
            {
              type: 'category',
              label: 'Cadena de Suministro',
              items: ['v2/actions/sbom', 'v2/actions/slsa-provenance', 'v2/actions/sign', 'v2/actions/policy-gate', 'v2/actions/fuzz'],
            },
            {
              type: 'category',
              label: 'Pruebas y Calidad',
              items: ['v2/actions/test-quality', 'v2/actions/security-gate', 'v2/actions/dast-scan', 'v2/actions/api-scan', 'v2/actions/compliance-report', 'v2/actions/setup-env'],
            },
            {
              type: 'category',
              label: 'Especializado',
              items: ['v2/actions/mobile-scan', 'v2/actions/smart-contract-audit', 'v2/actions/llm-scan', 'v2/actions/cloud-scan', 'v2/actions/license-scan'],
            },
          ],
        },
        {
          type: 'category',
          label: 'Los 10 Workflows',
          items: [
            'v2/workflows/framework',
            'v2/workflows/container-security',
            'v2/workflows/iac-security',
            'v2/workflows/supply-chain',
            'v2/workflows/dast',
            'v2/workflows/api-security',
            'v2/workflows/mobile-security',
            'v2/workflows/cloud-security',
            'v2/workflows/license-compliance',
            'v2/workflows/continuous-monitoring',
          ],
        },
        {
          type: 'category',
          label: 'Dominios de Seguridad',
          items: [
            'v2/dominios/web-apps',
            'v2/dominios/mobile',
            'v2/dominios/smart-contracts',
            'v2/dominios/genai-llm',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '👋 Introducción',
      link: {
        type: 'doc',
        id: 'README',
      },
      items: [
        'introduccion/desarrollo',
        'introduccion/guia-integracion',
        {
          type: 'category',
          label: 'Metodología OSDO',
          items: [
            'introduccion/marco-de-trabajo',
            'introduccion/adopcion-metodologia',
            'introduccion/best-practices',
            'introduccion/certificaciones',
            'introduccion/roadmap-certificaciones',
            'introduccion/faq',
          ]
        },
        {
          type: 'category',
          label: 'Integracion Continua (CI)',
          link: {
            type: 'doc',
            id: 'introduccion/integracion-continua-ci/README',
          },
          items: [
            'introduccion/integracion-continua-ci/flujo-de-trabajo',
            'introduccion/integracion-continua-ci/herramientas',
          ]
        },
        {
          type: 'category',
          label: 'Entrega Continua (CD)',
          link: {
            type: 'doc',
            id: 'introduccion/entrega-continua-cd/README',
          },
          items: [
            'introduccion/entrega-continua-cd/flujo-de-trabajo',
            'introduccion/entrega-continua-cd/herramientas',
          ]
        },
        'introduccion/monitorizacion',
      ],
    },
    {
      type: 'category',
      label: 'Infrastructura',
      link: {
        type: 'doc',
        id: 'infrastructura/README',
      },
      items: [
        'infrastructura/osdo-cli',

        {
          type: 'category',
          label: 'GitLab',
          link: {
            type: 'doc',
            id: 'infrastructura/gitlab/README',
          },
          items: [
            'infrastructura/gitlab/ci-cd',
            'infrastructura/gitlab/runner',
          ]
        },
        {
          type: 'category',
          label: 'GitHub',
          link: {
            type: 'doc',
            id: 'infrastructura/github/README',
          },
          items: [
            'infrastructura/github/ci-cd',
            'infrastructura/github/runner',
          ]
        },
        {
          type: 'category',
          label: 'Jenkins',
          link: {
            type: 'doc',
            id: 'infrastructura/jenkins/README',
          },
          items: [
            'infrastructura/jenkins/ci-cd',
            'infrastructura/jenkins/instalacion',
          ]
        },
        {
          type: 'category',
          label: 'CertManager',
          link: {
            type: 'doc',
            id: 'infrastructura/certmanager/README',
          },
          items: [
            'infrastructura/certmanager/instalacion',
          ]
        },
        {
          type: 'category',
          label: 'AppSec',
          link: {
            type: 'doc',
            id: 'infrastructura/appsec/README',
          },
          items: [
            'infrastructura/appsec/instalacion',
          ]
        },
        {
          type: 'category',
          label: 'Traefik',
          link: {
            type: 'doc',
            id: 'infrastructura/traefik/README',
          },
          items: [
            'infrastructura/traefik/instalacion',
          ]
        },
        {
          type: 'category',
          label: 'Argo CD',
          link: {
            type: 'doc',
            id: 'infrastructura/argocd/README',
          },
          items: [
            'infrastructura/argocd/instalacion',
            'infrastructura/argocd/jobs',
            'infrastructura/argocd/secrets',
          ]
        },
        {
          type: 'category',
          label: 'Harbor',
          link: {
            type: 'doc',
            id: 'infrastructura/harbor/README',
          },
          items: [
            'infrastructura/harbor/instalacion',
            'infrastructura/harbor/cuentas-automaticas',
          ]
        },
        {
          type: 'category',
          label: 'Sonarqube',
          link: {
            type: 'doc',
            id: 'infrastructura/sonarqube/README',
          },
          items: [
            'infrastructura/sonarqube/instalacion',
          ]
        },
        {
          type: 'category',
          label: 'Dependency-Track',
          link: {
            type: 'doc',
            id: 'infrastructura/dependency-track/README',
          },
          items: [
            'infrastructura/dependency-track/instalacion',
            'infrastructura/dependency-track/proyecto',
          ]
        },
        {
          type: 'category',
          label: 'DefectDojo',
          link: {
            type: 'doc',
            id: 'infrastructura/defectdojo/README',
          },
          items: [
            'infrastructura/defectdojo/instalacion',
            'infrastructura/defectdojo/jerarquia-de-producto'
          ]
        },
        {
          type: 'category',
          label: 'Dokploy',
          link: {
            type: 'doc',
            id: 'infrastructura/dokploy/README',
          },
          items: [
            'infrastructura/dokploy/instalacion',
            'infrastructura/dokploy/registry',
            `infrastructura/dokploy/proveedores-git`,
          ]
        },
        {
          type: 'category',
          label: 'GlitchTip',
          link: {
            type: 'doc',
            id: 'infrastructura/glitchtip/README',
          },
          items: [
            'infrastructura/glitchtip/instalacion',
            'infrastructura/glitchtip/proyecto',
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Desarrollo',
      items: [{
        type: 'category',
        label: 'Git',
        link: {
          type: 'doc',
          id: 'desarrollo/git/README',
        },
        items: [
          {
            type: 'doc',
            id: 'desarrollo/git/conceptos-basicos'
          },
          {
            type: 'doc',
            id: 'desarrollo/git/git-flow'
          },
          {
            type: 'doc',
            id: 'desarrollo/git/conventionalcommits'
          },
          {
            type: 'category',
            label: 'Hooks',
            link: {
              type: 'doc',
              id: 'desarrollo/git/hooks/README',
            },
            items: [
              {
                type: 'category',
                label: 'Pre-commit',
                items: [
                  'desarrollo/git/hooks/pre-commit/php',
                ]
              }
            ]
          }
        ]
      },
      {
        type: 'category',
        label: 'Threat Modeling',
        link: {
          type: 'doc',
          id: 'desarrollo/threatmodeling/README',
        },
        items: []
      }],
    },
    {
      type: 'category',
      label: 'CI',
      link: {
        type: 'doc',
        id: 'ci/index',
      },
      items: [
        {
          type: 'category',
          label: 'Preparación',
          link: {
            type: 'doc',
            id: 'ci/preparacion/README',
          },
          items: [
            'ci/preparacion/php',
            'ci/preparacion/node',
          ]
        },
        {
          type: 'category',
          label: 'Fugas de contraseñas',
          link: {
            type: 'doc',
            id: 'ci/fugas-de-contrasenas/README',
          },
          items: [
            'ci/fugas-de-contrasenas/gitleaks'
          ]
        },
        {
          type: 'category',
          label: 'SBOM',
          link: {
            type: 'doc',
            id: 'ci/sbom/README',
          },
          items: [
            {
              type: 'category',
              label: 'CycloneDX',
              link: {
                type: 'doc',
                id: 'ci/sbom/cyclonedx/README',
              },
              items: ['ci/sbom/cyclonedx/php', 'ci/sbom/cyclonedx/node']
            }
          ]
        },
        {
          type: 'category',
          label: 'Testing',
          link: {
            type: 'doc',
            id: 'ci/testing/README',
          },
          items: ['ci/testing/php']
        },
        {
          type: 'category',
          label: 'SAST',
          link: {
            type: 'doc',
            id: 'ci/sast/README',
          },
          items: [
            'ci/sast/sonarqube'
          ]
        },
        {
          type: 'category',
          label: 'Contenedores',
          link: {
            type: 'doc',
            id: 'ci/contenedores/README',
          },
          items: [
            'ci/contenedores/linting',
            'ci/contenedores/construccion',
            'ci/contenedores/analisis',
            'ci/contenedores/publicacion',
            'ci/contenedores/firma',
          ]

        },
        {
          type: 'category',
          label: 'DAST',
          link: {
            type: 'doc',
            id: 'ci/dast/README',
          },
          items: ['ci/dast/owasp-zap']
        },
        'ci/integraciones-monitorizacion',
      ],
    },
    {
      type: 'category',
      label: 'CD ',
      link: {
        type: 'doc',
        id: 'cd/index',
      },
      items: [
        {
          type: 'category',
          label: 'GitOps',
          link: {
            type: 'doc',
            id: 'cd/gitops/README',
          },
          items: [

          ]
        },
      ]
    },
  ],


};

module.exports = sidebars;
